USE [master]
GO

/****** Object:  Database [TP3]    Script Date: 11/4/2018 18:27:17 ******/
CREATE DATABASE [TP3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TP3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TP3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TP3] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TP3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TP3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TP3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TP3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TP3] SET ARITHABORT OFF 
GO

ALTER DATABASE [TP3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TP3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TP3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TP3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TP3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TP3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TP3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TP3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TP3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TP3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TP3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TP3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TP3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TP3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TP3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TP3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TP3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TP3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TP3] SET  MULTI_USER 
GO

ALTER DATABASE [TP3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TP3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TP3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TP3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TP3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TP3] SET QUERY_STORE = OFF
GO

USE [TP3]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TP3] SET  READ_WRITE 
GO


USE [TP3]
GO

/****** Object:  Table [dbo].[PARTIDAS]    Script Date: 11/4/2018 18:28:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PARTIDAS](
	[IDPARTIDA] [int] NOT NULL,
	[JUGADORGANADOR] [nvarchar](50) NOT NULL,
	[PUNTAJE] [int] NOT NULL,
	[CARTAS] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_PARTIDAS] PRIMARY KEY CLUSTERED 
(
	[IDPARTIDA] ASC,
	[JUGADORGANADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO





