USE [OPERATIVA]
GO

/****** Object:  Table [dbo].[LOTES]    Script Date: 19/11/2017 14:56:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOTES](
	[IDLOTE] [int] IDENTITY(1,1) NOT NULL,
	[IDENVASE] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[DISPONIBLES] [int] NOT NULL,
	[PRECIOCOMPRA] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_LOTES] PRIMARY KEY CLUSTERED 
(
	[IDLOTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOTES]  WITH CHECK ADD  CONSTRAINT [FK_LOTES_ENVASES] FOREIGN KEY([IDENVASE])
REFERENCES [dbo].[ENVASES] ([IDENVASE])
GO

ALTER TABLE [dbo].[LOTES] CHECK CONSTRAINT [FK_LOTES_ENVASES]
GO


