USE [OPERATIVA]
GO

/****** Object:  Table [dbo].[VENTAS]    Script Date: 19/11/2017 10:04:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VENTAS](
	[IDCLIENTE] [int] NOT NULL,
	[IDLOTE] [int] NOT NULL,
	[IDENVASE] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[PRECIOVENTA] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_VENTAS] PRIMARY KEY CLUSTERED 
(
	[IDCLIENTE] ASC,
	[IDLOTE] ASC,
	[IDENVASE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_CLIENTES] FOREIGN KEY([IDCLIENTE])
REFERENCES [dbo].[CLIENTES] ([IDCLIENTE])
GO

ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [FK_VENTAS_CLIENTES]
GO

ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_ENVASES] FOREIGN KEY([IDENVASE])
REFERENCES [dbo].[ENVASES] ([IDENVASE])
GO

ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [FK_VENTAS_ENVASES]
GO

ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_LOTES] FOREIGN KEY([IDLOTE])
REFERENCES [dbo].[LOTES] ([IDLOTE])
GO

ALTER TABLE [dbo].[VENTAS] CHECK CONSTRAINT [FK_VENTAS_LOTES]
GO

